# Generated by Django 4.2.5 on 2023-09-23 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='data_de_nascimento',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telefone',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='recipes/covers/%Y/%m/%d/', verbose_name='Imagem de perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
