# Generated by Django 4.2.5 on 2023-09-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_profile_data_de_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='Profile/covers/%Y/%m/%d/', verbose_name='Imagem de perfil'),
        ),
    ]
